'use client';

import { useEffect } from 'react';

/**
 * PushRegistration — Registers the Workbox-generated service worker
 * and handles push subscription state.
 *
 * The SW is now generated by @ducanh2912/next-pwa (Workbox) and
 * includes our custom push notification handlers from src/worker/index.ts.
 */
export function PushRegistration() {
    useEffect(() => {
        if ('serviceWorker' in navigator && 'PushManager' in window) {
            // The PWA plugin auto-registers the SW via its own script.
            // We just check for existing push subscriptions here.
            navigator.serviceWorker.ready
                .then((registration) => {
                    console.log('Service Worker ready with scope:', registration.scope);
                    return registration.pushManager.getSubscription();
                })
                .then((subscription) => {
                    if (subscription) {
                        // Already subscribed — could sync with server if needed
                        console.log('Push subscription active');
                    }
                })
                .catch((error) => {
                    console.error('Service Worker / Push error:', error);
                });
        }
    }, []);

    return null; // This component doesn't render anything visible
}
